# Generated by Django 5.0 on 2024-01-06 08:27

import common.modules.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': 'Sub Categories'},
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.subcategory'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=common.modules.fields.CaseInsensitiveCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='product.category'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=common.modules.fields.CaseInsensitiveCharField(max_length=255),
        ),
    ]
