# Generated by Django 5.0 on 2024-01-06 08:37

import common.modules.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_subcategory_options_product_subcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=common.modules.fields.CaseInsensitiveCharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=common.modules.fields.CaseInsensitiveCharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
